#define MAP_SIZE_Y 15
#define MAP_SIZE_X 20

const u8 sideEnterMaps[]={1,2,3,11};
const u8 topEnterMaps[]={4,5,8,9};
const u8 bottomEnterMaps[]={0,5,6,7,10,12};

const u8 maps[13][15][20]= {
	
	{{topLeftWall,topWall,topWall,topWall,topWall,topWall,topWall,blank,blank,blank,blank,blank,blank,topWall,topWall,topWall,topWall,topWall,topWall,topRightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,rightWall},
	{blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank},
	{leftWall,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{bottomLeftWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomRightWall}},
	
	{{topLeftWall,topWall,topWall,topWall,topWall,topWall,topWall,blank,blank,blank,blank,blank,blank,topWall,topWall,topWall,topWall,topWall,topWall,topRightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{bottomLeftWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,blank,blank,blank,blank,blank,blank,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomRightWall}},
	
	{{topLeftWall,topWall,topWall,topWall,topWall,topWall,topRightWall,blank,blank,blank,blank,blank,blank,topLeftWall,topWall,topWall,topWall,topWall,topWall,topRightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{bottomLeftWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomRightWall,blank,blank,blank,blank,blank,blank,bottomLeftWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomRightWall}},
	
	{{topLeftWall,topWall,topWall,topWall,topWall,topWall,topWall,blank,blank,blank,blank,blank,blank,topWall,topWall,topWall,topWall,topWall,topWall,topRightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{bottomLeftWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,blank,blank,blank,blank,blank,blank,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomRightWall}},
	
	{{topLeftWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topRightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,rightWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,leftWall,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,rightWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,leftWall,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{bottomLeftWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,blank,blank,blank,blank,blank,blank,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomRightWall}},
	
	{{topLeftWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topRightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,rightWall},
	{blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank},
	{leftWall,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,blank,blank,blank,blank,verticalWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{bottomLeftWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomRightWall}},
	
	{{topLeftWall,topWall,topWall,topWall,topWall,topWall,topWall,blank,blank,blank,blank,blank,blank,topWall,topWall,topWall,topWall,topWall,topWall,topRightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,rightWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,leftWall,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,rightWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,leftWall,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{bottomLeftWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomRightWall}},
	
	{{topLeftWall,topWall,topWall,topWall,topWall,topWall,topRightWall,blank,blank,blank,blank,blank,blank,topLeftWall,topWall,topWall,topWall,topWall,topWall,topRightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{bottomLeftWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomRightWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomLeftWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomRightWall}},
	
	{{topLeftWall,topWall,topWall,topWall,topWall,topWall,topRightWall,topWall,topWall,topWall,topWall,topWall,topWall,topLeftWall,topWall,topWall,topWall,topWall,topWall,topRightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{bottomLeftWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomRightWall,blank,blank,blank,blank,blank,blank,bottomLeftWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomRightWall}},
	
	{{topLeftWall,topWall,topWall,topWall,topWall,topWall,topRightWall,topWall,topWall,topWall,topWall,topWall,topWall,topLeftWall,topWall,topWall,topWall,topWall,topWall,topRightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank},
	{topLeftWall,topWall,topWall,topWall,topWall,topWall,topWall,blank,blank,blank,blank,blank,blank,topWall,topWall,topWall,topWall,topWall,topWall,topRightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{bottomLeftWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,blank,blank,blank,blank,blank,blank,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomRightWall}},
	
	{{topLeftWall,topWall,topWall,topWall,topWall,topWall,topRightWall,blank,blank,blank,blank,blank,blank,topLeftWall,topWall,topWall,topWall,topWall,topWall,topRightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank},
	{topLeftWall,topWall,topWall,topWall,topWall,topWall,topWall,blank,blank,blank,blank,blank,blank,topWall,topWall,topWall,topWall,topWall,topWall,topRightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{bottomLeftWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomRightWall}},
	
	{{topLeftWall,topWall,topWall,topWall,topWall,topWall,topRightWall,blank,blank,blank,blank,blank,blank,topLeftWall,topWall,topWall,topWall,topWall,topWall,topRightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{topLeftWall,topWall,topWall,topWall,topWall,topWall,topWall,blank,blank,blank,blank,blank,blank,topWall,topWall,topWall,topWall,topWall,topWall,topRightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{bottomLeftWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,blank,blank,blank,blank,blank,blank,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomRightWall}},
	
	{{topLeftWall,topWall,topWall,topWall,topWall,topWall,topWall,blank,blank,blank,blank,blank,blank,topWall,topWall,topWall,topWall,topWall,topWall,topRightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,rightWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,leftWall,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,rightWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,topWall,leftWall,blank,blank,blank,blank,blank},
	{blank,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,blank},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,rightWall,blank,blank,blank,blank,blank,blank,blank,blank,leftWall,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{leftWall,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,blank,rightWall},
	{bottomLeftWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomWall,bottomRightWall}},
	};

	 